# Lock and lower brightness after 3 minutes
listener {
    timeout = 180
    on-timeout = loginctl lock-session && brightnessctl -s set 10%
    on-resume = brightnessctl -r
}

# Screen off after 5 minutes
listener {
    timeout = 300
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r
}

# Suspend after 10 minutes
listener {
    timeout = 600
    on-timeout = systemctl suspend-then-hibernate
}
